services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    # env_file:
    #   - ./env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/wordpress
    # env_file:
    #   - ./env
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception_network
    volumes:
      - mariadb:/var/lib/mysql/
    # env_file:
    #   - ./env
    expose:
      - "3306"
    restart: always

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/${USER}/Desktop/wordpress
  mariadb:
    name : mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/${USER}/Desktop/mariadb


# docker-compose up -d --build        <===== launch
# docker compose down                 <===== delete dockers
# docker rmi volume_name              <===== delete volume
# docker volume rm volume_name        <===== delete volume
# docker volume ls                    <===== listing volumes
# docker network ls                   <===== listing networks
# docker ps -a                        <===== listing the dockers