services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - "80:80"
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception_network
    volumes:
      - mariadb:/var/lib/mysql/wp_db

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/abouhlel/Desktop/wordpress
  mariadb:
    name : mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/abouhlel/Desktop/mariadb


# docker-compose up --build