services:
  nginx:
    build: ./requirements/nginx
    image: nginx_img
    ports:
      - "80:80"
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    image: php_img
    networks:
      - inception_network

  mariadb:
    build: ./requirements/mariadb
    image: md_img
    networks:
      - inception_network

networks:
  inception_network:
    name: inception_network
    driver: bridge

#docker-compose up --build